services:
  # train-devcontainer:
  #   image: mcr.microsoft.com/devcontainers/python:1-3.12-bullseye
  #   volumes:
  #     - .:/workspace:cached
  #   command: sleep infinity

  train:
    build: ./train
    volumes:
      - ./train/models:/models

  # PostgreSQL database for our services
  database:
    build: ./database
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./database/.env

  # MLFlow server for experiment tracking (uses the database)
  experiment-tracking:
    build: ./experiment-tracking
    ports:
      - 5000:5000
    depends_on:
      - database

  # prefect server
  orchestration:
    build: ./orchestration
    ports:
      - 4200:4200

  # frontend-devcontainer:
  #   image: mcr.microsoft.com/devcontainers/python:1-3.13-bullseye
  #   volumes:
  #     - .:/workspace:cached
  #     - ./train/models:/workspace/frontend/models
  #   command: sleep infinity

  frontend:
    build: ./frontend
    ports:
      - 9696:9696
    volumes:
      - ./train/models:/app/models

  # deploy-batch-devcontainer:
  #   image: mcr.microsoft.com/devcontainers/python:1-3.13-bullseye
  #   volumes:
  #     - .:/workspace:cached
  #     - ./train/models:/workspace/deploy-batch/models
  #     - ./train/data:/workspace/deploy-batch/data
  #   command: sleep infinity

  deploy-batch:
    build: ./deploy_batch
    volumes:
      - ./train/models:/models
      - ./train/data:/data
      - ./deploy-batch/batch-output:/batch-output

volumes:
  postgres-data:
