services:
  # train-devcontainer:
  #   image: mcr.microsoft.com/devcontainers/python:1-3.12-bullseye
  #   volumes:
  #     - .:/workspace:cached
  #   command: sleep infinity

  train:
    build: ./train

  # PostgreSQL database for our services
  database:
    build: ./database
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./database/.env

  # MLFlow server for experiment tracking (uses the database)
  experiment-tracking:
    build: ./experiment-tracking
    ports:
      - 5000:5000
    depends_on:
      - database

  # prefect server
  orchestration:
    build: ./orchestration
    ports:
      - 4200:4200

volumes:
  postgres-data:
